# Generated by Django 6.1.1 on 2026-09-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='existing_conditions',
            field=models.TextField(blank=True, help_text='Comma-separated list of existing conditions'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.FloatField(blank=True, help_text='Height in centimetres (optional)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='known_allergies',
            field=models.TextField(blank=True, help_text='Comma-separated list of known allergies'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.FloatField(blank=True, help_text='Weight in kilograms (optional)', null=True),
        ),
    ]
