# Generated by Django 6.1.1 on 2026-09-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('dosage', models.CharField(blank=True, max_length=200)),
                ('frequency', models.CharField(blank=True, max_length=200)),
                ('duration', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'medicines',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prescriptions/')),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('cleaned_ocr_text', models.TextField(blank=True)),
                ('ocr_engine', models.CharField(blank=True, max_length=50)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('low_confidence', models.BooleanField(default=False)),
                ('warning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
