# Generated by Django 6.1.1 on 2026-09-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('snippet', models.TextField(blank=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('chunk_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_sources',
            },
        ),
        migrations.CreateModel(
            name='ExtractedSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('entity_type', models.CharField(blank=True, default='symptom', max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('start_char', models.IntegerField(blank=True, null=True)),
                ('end_char', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'extracted_symptoms',
            },
        ),
        migrations.CreateModel(
            name='SymptomAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_input', models.TextField(help_text='Original user symptom description')),
                ('cleaned_input', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('respiratory', 'Respiratory'), ('digestive', 'Digestive'), ('neurological', 'Neurological'), ('dermatological', 'Dermatological'), ('musculoskeletal', 'Musculoskeletal'), ('general', 'General')], max_length=50)),
                ('category_confidence', models.FloatField(blank=True, null=True)),
                ('duration_text', models.CharField(blank=True, max_length=200)),
                ('severity_text', models.CharField(blank=True, max_length=200)),
                ('body_area', models.CharField(blank=True, max_length=200)),
                ('workflow_status', models.JSONField(blank=True, default=dict)),
                ('llm_response', models.TextField(blank=True)),
                ('safety_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'symptom_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('agent_steps', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'workflow_runs',
            },
        ),
    ]
