# Generated by Django 6.1.1 on 2026-09-22 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symptoms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extractedsymptom',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_symptoms', to='symptoms.symptomanalysis'),
        ),
        migrations.AddField(
            model_name='analysissource',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='symptoms.symptomanalysis'),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_run', to='symptoms.symptomanalysis'),
        ),
    ]
